services:
  postgres:
    image: postgres:17
    container_name: webdesign-postgres
    environment:
      POSTGRES_USER: webdesignuser
      POSTGRES_PASSWORD: webdesignmdp
      POSTGRES_DB: webdesigndb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webdesignuser -d webdesigndb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
